spring:
  datasource:
    url: jdbc:postgresql://localhost:15433/demo_db_local?currentSchema=test
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
