spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:15433/demo_db_local?currentSchema=demo
    username: demo
    password: demo
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validateOnMigrate: false


logging:
  level:
    org.flywaydb: INFO
    root: info


server:
  port: 8888
  error.whitelabel.enabled: false
  tomcat:
    mbeanregistry:
      enabled: true
  forward-headers-strategy: native
